### ISSUE TITLE
updatable is a vote invariant for create vote

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#188]
Behaviour: Manage votes/create vote;updatable is a vote invariant

@tested_feature("Manage votes")

@tested_operation("create vote")

@tested_behaviour("updatable is a vote invariant")

[Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9386718b-3caf-4152-8386-0df9deeb35d3-53971969-fee5-4442-a283-98d7f5b2c94f-98a3c707-ab07-43a7-9f7c-2475aa3852db)

**Comment by colorimeter** [comment]
Define "updatable"

**Comment by magwas** [comment]
A newly introduced property of the vote. Search the design doc for all of its uses. I mean when I will commit it...
