### ISSUE TITLE
BeatTable.getPair

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#238]
Behaviour: Supporting functionality/BeatTable;the pair related to a and b can be obtained

@tested_feature("Supporting functionality")

@tested_operation("BeatTable")

@tested_behaviour("the pair related to a and b can be obtained")

by getPair(Choice a, Choice b)

[Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#de4b570a-17b0-4872-a614-22acfca5eea2-b46d19bb-27bf-46bf-9096-cea0caec2ca8-96b3aa1a-d34b-4c9b-bde2-643835f5ee75)

**Comment by valentinbujdoso** [comment]
obsolate
