### ISSUE TITLE
add choice validates input

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#34]
Behaviour: Manage votes/Add choice; validates inputs
 @tested_feature("Manage votes")
 @tested_operation("Add choice")
 @tested_behaviour("validates inputs")
 
            
String voteId: id of existing vote
String adminKey: same as vote's adminKey, or "user"
String choiceId: id of existing choice in the vote with voteid

[Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9386718b-3caf-4152-8386-0df9deeb35d3-d311158f-1d7b-4288-86d2-a258d7a63741-af499e94-b21e-4295-8f22-efe9e9e0be15)

**Comment by valentinbujdoso** [comment]
@magwas Ez nincs veletlen keszen a ChoiceManager osztalyban?
