### ISSUE TITLE
add choice returns choice id

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#35]
Behaviour: Manage votes/Add choice; returns a unique choice id
 @tested_feature("Manage votes")
 @tested_operation("Add choice")
 @tested_behaviour("returns a unique choice id")

 [Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9386718b-3caf-4152-8386-0df9deeb35d3-d311158f-1d7b-4288-86d2-a258d7a63741-7683ba2c-37ee-47ad-a990-5dd1e1de20b4)

**Comment by lbarjak** [comment]
Megcsináltam gyakorlásképpen de lehet, hogy vagy ez nem fog kelleni, vagy a AddChoiceAddsChoiceToTheVoteTest.java -ból ki kell venni ezt a tesztet, hacsak nem kell valamiért mindkettő.

**Comment by magwas** [comment]
a #155 pull requestet akkor lezárom, mert duplikált kód. Jó lessz az AddChoiceAddsChoiceToTheVoteTest-ben.
