### ISSUE TITLE
show vote validates inputs

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#39]
Behaviour: Manage votes/show vote; validates inputs
 @tested_feature("Manage votes")
 @tested_operation("show vote")
 @tested_behaviour("validates inputs")
 
            
String voteId: id of existing vote
String adminKey: same as vote's adminKey for private votes, "anon" for public ones

 [Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9386718b-3caf-4152-8386-0df9deeb35d3-5c0244e2-2097-4b3b-abed-9dbefdcd45ac-519b79c6-86ed-43c9-ad3f-b44181b77027)

**Comment by valentinbujdoso** [comment]
.
