### ISSUE TITLE
delete choice validates input

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#41]
Behaviour: Manage votes/delete choice; validates inputs
 @tested_feature("Manage votes")
 @tested_operation("delete choice")
 @tested_behaviour("validates inputs")
 
            
String voteId: id of existing vote
String adminKey: same as vote's adminKey, or "user"
String choiceId: id of existing choice in the vote with voteid
         
 [Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9386718b-3caf-4152-8386-0df9deeb35d3-3044c21c-7606-4098-8176-9dd5b93c20ad-af499e94-b21e-4295-8f22-efe9e9e0be15)

**Comment by valentinbujdoso** [comment]
It is on the #43 branch's
