### ISSUE TITLE
delete choice, "user" case

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#42]
Behaviour: Manage votes/delete choice; if "user" is used as adminKey, then the user must be the one who added the choice and canAddIn be true
 @tested_feature("Manage votes")
 @tested_operation("delete choice")
 @tested_behaviour("if "user" is used as adminKey, then the user must be the one who added the choice and canAddIn be true")
 
 [Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9386718b-3caf-4152-8386-0df9deeb35d3-3044c21c-7606-4098-8176-9dd5b93c20ad-f03d1e89-5f2b-4afd-9e68-9c2831d09ca4)

**Comment by valentinbujdoso** [comment]
@magwas Szoval, ha az adminKey az "user" es a canAddIn true valamint a Choice username = ?.
Itt a Choice username-nek "user"-nek kell lennie, vagy honnan tudom hogy a user az megegyezik a letrehozo userrel?
