### ISSUE TITLE
modify choice modifies the string of the choice

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#50]
Behaviour: Manage votes/modify choice; modifies the string of the choice
 @tested_feature("Manage votes")
 @tested_operation("modify choice")
 @tested_behaviour("modifies the string of the choice")

 [Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9386718b-3caf-4152-8386-0df9deeb35d3-9a443205-d873-4413-8c2d-d6e1e7e5e520-a19677f3-b2c0-4ba3-8f4a-82f93ee41022)

**Comment by valentinbujdoso** [comment]
Ezt megcsinaltam meg valamelyik ezelottivel.

**Comment by magwas** [comment]
A hozzá tartozó teszteset annotációja rossz:
@tested_feature("Manage votes")
@tested_operation("modify vote")
@tested_behaviour("validates inputs")
@Test
public void proper_voteId_choiceId_and_adminKey_does_modify_choice() 

Megcsinálod garanciában?

**Comment by valentinbujdoso** [comment]
Meg persze. Délután ránézek
