### ISSUE TITLE
obtain ballots observes invariants

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#56]
Behaviour: Manage votes/Obtain ballot; vote invariants
 @tested_feature("Manage votes")
 @tested_operation("Obtain ballot")
 @tested_behaviour("vote invariants")
 
            
the following vote parameters are invariant:
- vote id
- admin key
- needed assurances
- counted assurances
- is private
- creation time

[Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9386718b-3caf-4152-8386-0df9deeb35d3-8715adde-bba4-4000-bbd5-d40f1cccaf22-248342eb-7583-480e-a2ef-471863169423)

**Comment by valentinbujdoso** [comment]
This behaviour is missing from the Deviaton model.
