### ISSUE TITLE
obtain ballot anon adminkey case

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#58]
Behaviour: Manage votes/Obtain ballot; if adminKey is anon, the user should have all the neededAssurances
 @tested_feature("Manage votes")
 @tested_operation("Obtain ballot")
 @tested_behaviour("if adminKey is anon, the user should have all the neededAssurances")

[Deviation in model](http://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9386718b-3caf-4152-8386-0df9deeb35d3-8715adde-bba4-4000-bbd5-d40f1cccaf22-ea84e342-2789-4fa9-97a9-116a996f966f)

**Comment by valentinbujdoso** [comment]
Could you explain this a little bit more detailed?
