### ISSUE TITLE
hungarian API documentation

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#79]
https://docs.google.com/document/d/140HQiYUZlEsGaWtfCx3qTSWjWw1tLyU5zjm99Ug3FY4/edit

**Comment by magwas** [comment]
everyone, please comment.

**Comment by utopszkij** [comment]
V 1.01 Szabó Károllyal konzultálás alapján átdolgozott új verzió

https://docs.google.com/document/d/1OfiW5jRzdRuli-4wmBedvsatGIfEgHGzq5Cm5cAzKzk/edit?usp=sharing
